include: package:flutter_lints/flutter.yaml


analyzer:
  plugins:
    - custom_lint


custom_lint:
  rules:
    # Explicitly disable one lint rule
    # - missing_provider_scope: true
    - avoid_manual_providers_as_generated_provider_dependency: true

linter:
  rules:
    - prefer_const_constructors_in_immutables: true